develop: true

config_params:
 - "daemon"
 - "process_id_file"
 - "setup_mode"
 - "videodevice"
 - "v4l2_palette"
 - "input"
 - "norm"
 - "frequency"
 - "rotate"
 - "width"
 - "height"
 - "framerate"
 - "minimum_frame_time"
 - "netcam_url"
 - "netcam_userpass"
 - "netcam_http"
 - "netcam_proxy"
 - "netcam_tolerant_check"
 - "auto_brightness"
 - "brightness"
 - "contrast"
 - "saturation"
 - "hue"
 - "roundrobin_frames"
 - "roundrobin_skip"
 - "switchfilter"
 - "threshold"
 - "threshold_tune"
 - "noise_level"
 - "noise_tune"
 - "despeckle"
 - "area_detect"
 - "mask_file"
 - "smart_mask_speed"
 - "lightswitch"
 - "minimum_motion_frames"
 - "pre_capture"
 - "post_capture"
 - "gap"
 - "max_mpeg_time"
 - "output_all"
 - "output_normal"
 - "output_motion"
 - "quality"
 - "ppm"
 - "ffmpeg_cap_new"
 - "ffmpeg_cap_motion"
 - "ffmpeg_timelapse"
 - "ffmpeg_timelapse_mode"
 - "ffmpeg_bps"
 - "ffmpeg_variable_bitrate"
 - "ffmpeg_video_codec"
 - "ffmpeg_deinterlace"
 - "snapshot_interval"
 - "locate"
 - "text_right"
 - "text_left"
 - "text_changes"
 - "text_event"
 - "text_double"
 - "target_dir"
 - "snapshot_filename"
 - "jpeg_filename"
 - "movie_filename"
 - "timelapse_filename"
 - "webcam_port"
 - "webcam_quality"
 - "webcam_motion"
 - "webcam_maxrate"
 - "webcam_localhost"
 - "webcam_limit"
 - "control_port"
 - "control_localhost"
 - "control_html_output"
 - "control_authentication"
 - "track_type"
 - "track_auto"
 - "track_port"
 - "track_motorx"
 - "track_motory"
 - "track_maxx"
 - "track_maxy"
 - "track_iomojo_id"
 - "track_step_angle_x"
 - "track_step_angle_y"
 - "track_move_wait"
 - "track_speed"
 - "track_stepsize"
 - "quiet"
 - "on_event_start"
 - "on_event_end"
 - "on_picture_save"
 - "on_motion_detected"
 - "on_area_detected"
 - "on_movie_start"
 - "on_movie_end"
 - "on_camera_lost"
 - "sql_log_image"
 - "sql_log_snapshot"
 - "sql_log_mpeg"
 - "sql_log_timelapse"
 - "sql_query"
 - "pgsql_db"
 - "pgsql_host"
 - "pgsql_user"
 - "pgsql_password"
 - "pgsql_port"
 - "video_pipe"
 - "motion_video_pipe"